comment:
  image:
    repository: fflvladimir/comment:1.0
  service:
    externalPort: 9292

post:
  image:
    repository: fflvladimir/post:1.0
  service:
    externalPort: 5000

ui:
  image:
    repository: fflvladimir/ui:1.0
  service:
    externalPort: 9292

mongodb:
  usePassword: false
