version: '3.3'

services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      back_net:
          aliases:
            - prometheus
      front_net:
          aliases:
            - prometheus

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks: 
      back_net:
        aliases:
          - node-exporter
      front_net:
        aliases:
          - node-exporter

  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
        back_net:
            aliases:
              - post_db
              - comment_db
        
  ui:
    # build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - protocol: tcp
        published: ${FRONT_PORT}
        target: 9292
    networks:
        front_net:
            aliases:
              - ui
  post:
    # build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
        back_net:
            aliases:
              - post
        front_net:
            aliases:
              - post
  comment:
    # build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
        back_net:
            aliases:
              - comment
        front_net:
            aliases:
              - comment

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
